#! /usr/bin/python3

# import necessary libraries
import sys
import base64
import subprocess

argv = sys.argv
# Checking the file is given as Command Line Argument or not
# If not given print "Not Found" and exit the program

if len(argv) < 2:
        print("set_env <program name>")
        sys.exit(0)

# Setting the Environment path with filename
env_path = f"/home/username/project/Environment/{argv[1]}/"

# Checking the file exist or not
# if not print "File not Found"
# if the file exist convert the python file into Linux Executables
# Store it in the path /program_lab/executables/
try:
        exe = subprocess.run(["pyinstaller", f"{env_path}{argv[1]}.py", "--onefile"])
        exe_path = f"/home/karthi/project/Executables/dist/{argv[1]}"

        with open(exe_path, 'rb') as fp:
                with open("/program_lab/executables/" + argv[1], 'wb') as fp2:
                        fp2.write(fp.read())
        exe = subprocess.run(["chmod",  "+x", f"/program_lab/executables/{argv[1]}"])

except FileNotFoundError:
        print(f"File: `{argv[1]}.py` Not Found!!!")

# if the file exist it encode the file
# Store it in the path /program_lab/public_test/
try:
        with open(f"{env_path}{argv[1]}.pub", 'r') as fp:
                with open("/program_lab/public_test/" + argv[1], 'wb') as fp2:
                        content = fp.read()
                        content = content.encode()
                        encoded_content = base64.b64encode(content)
                        fp2.write(encoded_content)

except FileNotFoundError:
        print(f"File: `{argv[1]}.pub` Not Found!!!")

# if the file exist it encode the file
# Store it in the path /program_lab/private_test/
try:
        with open(f"{env_path}{argv[1]}.pri", 'r') as fp:
                with open("/program_lab/private_test/" + argv[1], 'wb') as fp2:
                        content = fp.read()
                        content = content.encode()
                        encoded_content = base64.b64encode(content)
                        fp2.write(encoded_content)

except FileNotFoundError:
        print(f"File: `{argv[1]}.pri` Not Found!!!")

# if the file exist it encode the file
# Store it in the path /program_lab/Questions/
try:
        with open(f"{env_path}{argv[1]}.Q", 'r') as fp:
                with open("/program_lab/Questions/" + argv[1], 'w') as fp2:
                        content = fp.read()
                        fp2.write(content)

except FileNotFoundError:
        print(f"File: `{argv[1]}.Q` Not Found!!!")

print("Environment Sucessfully Created.... ")